feat: bet status completion
shapeitapp/shapeitapp pull request #51
Opened 2023-07-18 19:11 UTC by koukama

Fixes #23

2023-07-19 09:19 UTC, fmvilas requested changes

2023-07-19 09:19 UTC, fmvilas commented on src/app/projects/[ownerType]/[org]/[project]/cycles/[cycle]/layout.js
> +      console.log(scopes)
```suggestion
```

2023-07-19 09:19 UTC, fmvilas commented on src/app/projects/[ownerType]/[org]/[project]/cycles/[cycle]/layout.js
> +  console.log(`issues`, issues)
```suggestion
```

2023-07-19 09:19 UTC, fmvilas commented on src/app/projects/[ownerType]/[org]/[project]/cycles/[cycle]/layout.js
> +
This whole function could be reduced to something like this:

```js
return scopes.reduce((partialSum, scope) => partialSum + scope.progress.percentage, 0)
```

In any case, check the above is correct because I just did it from the top of my head 😅

2023-07-21 13:02 UTC, Amzani approved these changes
LGTM

2023-07-21 13:05 UTC, Amzani commented on src/components/Bet.js
> +import { useEffect, useState, useRef } from 'react'
@koukama looks like we not using any of theses hooks.

2023-07-21 13:14 UTC, merged

2023-07-21 15:24 UTC, fmvilas commented on src/app/projects/[ownerType]/[org]/[project]/cycles/[cycle]/layout.js
> +  return scopes.length != 0 ?
🤔 I think you don't need this line anymore. The second parameter of the `reduce` call (the 0) is precisely for that. But yeah, not really important. Just thought you'd like to know it :)